/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DateCalendar {
    'inputRef': HTMLInputElement;
    /**
    * The first name
    */
    'onChange': Function;
  }
  interface DatePicker {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLDateCalendarElement extends Components.DateCalendar, HTMLStencilElement {}
  var HTMLDateCalendarElement: {
    prototype: HTMLDateCalendarElement;
    new (): HTMLDateCalendarElement;
  };

  interface HTMLDatePickerElement extends Components.DatePicker, HTMLStencilElement {}
  var HTMLDatePickerElement: {
    prototype: HTMLDatePickerElement;
    new (): HTMLDatePickerElement;
  };
  interface HTMLElementTagNameMap {
    'date-calendar': HTMLDateCalendarElement;
    'date-picker': HTMLDatePickerElement;
  }
}

declare namespace LocalJSX {
  interface DateCalendar {
    'inputRef'?: HTMLInputElement;
    /**
    * The first name
    */
    'onChange'?: Function;
  }
  interface DatePicker {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'date-calendar': DateCalendar;
    'date-picker': DatePicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'date-calendar': LocalJSX.DateCalendar & JSXBase.HTMLAttributes<HTMLDateCalendarElement>;
      'date-picker': LocalJSX.DatePicker & JSXBase.HTMLAttributes<HTMLDatePickerElement>;
    }
  }
}


